### ISSUE TITLE
Adding additional data in the DRF api endpoint

### ISSUE THREAD

**Issue by khashashin** [khashashin/blemmy#3]
Im trying to create restaurant menu table for 2 years. And to create a Database i created model class like:
[cultina model class Week](https://github.com/khashashin/blemmy/blob/7be47bf4be1cbc61841b2c4388bca9c3ddf3138e/cultinadb/models.py#L134)

[stackoverflow question](https://stackoverflow.com/questions/45978099/adding-additional-data-in-the-drf-api-endpoint)

    YEARS = (
        (2017, 2017),
        # (2018, 2018),
    )
    WEEKS = (
        (1,1),(2,2),(3,3),(4,4),(5,5),(6,6),
        (7,7),(8,8),(9,9),(10,10),(11,11),(12,12),
        (13,13),(14,14),(15,15),(16,16),(17,17),(18,18),
        (19,19),(20,20),(21,21),(22,22),(23,23),(24,24),
        (25,25),(26,26),(27,27),(28,28),(29,29),(30,30),
        (31,31),(32,32),(33,33),(34,34),(35,35),(36,36),
        (37,37),(38,38),(39,39),(40,40),(41,41),(42,42),
        (43,43),(44,44),(45,45),(46,46),(47,47),(48,48),
        (49,49),(50,50),(51,51),(52,52),(53,53),
    )
    DAYS = (
        ('Montag',1),
        ('Dienstag',2),
        ('Mittwoch',3),
        ('Donnerstag',4),
        ('Freitag',5),
    )
    
    class Week(models.Model):
        country = CountryField(
            verbose_name='Land', blank=True, null=True, blank_label='Wochenspezialität ist aus ...')
        year = models.IntegerField(verbose_name='Jahr', choices=YEARS,
            null=True)
        week = models.SmallIntegerField(verbose_name='Woche' ,choices=WEEKS,
and my endpoints.py have:

    from wagtail.api.v2.endpoints import BaseAPIEndpoint
    
    from .models import Week, Ingredient, Menu
    
    class WeekAPIEndpoint(BaseAPIEndpoint):
        model = Week
    def register_endpoints(api_router):
        api_router.register_endpoint('week', WeekAPIEndpoint)
And if I follow the link __http://saad1.khashashin.com/api/v2/week__ i get this:

[![enter image description here][1]][1]

Can I somehow add data that will be equal "year" and "week" to this endpoint __http://saad1.khashashin.com/api/v2/week__ like here:

    {
        "meta": {
            "total_count": 2
        },
        "items": [
            {
                "id": 1,
                "year": 2017,
                "week": 22,
                "meta": {
                    "type": "cultinadb.Week",
                    "detail_url": "http://saad1.khashashin.com/api/v2/week/1/"
                }
            },
            {
                "id": 2,
                "year": 2017,
                "week": 21,
                "meta": {
                    "type": "cultinadb.Week",
                    "detail_url": "http://saad1.khashashin.com/api/v2/week/2/"
                }
            }
        ]
    }

from here __http://saad1.khashashin.com/api/v2/week/1__:

[![enter image description here][2]][2]

Its hard to explane for me. I just need them to be available before I click on the link __http://saad1.khashashin.com/api/v2/week/1__.

  [1]: https://i.stack.imgur.com/bXDev.png
  [2]: https://i.stack.imgur.com/2bcfB.png

**Comment by loleg** [comment]
Use the `listing_default_fields` option in your Endpoint as in [this example](https://github.com/datalets/blemmy/blob/openfarms/openfarms/endpoints.py#L26).

**Comment by khashashin** [comment]
![2017-08-31 3](https://user-images.githubusercontent.com/17837758/29927201-e9b119dc-8e65-11e7-923f-3a066878e8ef.png)
Thank you very much it works!!
